name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      GH_TOKEN: "${{ secrets.JPG_ACTION_TOKEN }}"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run make
      - name: Release-DMG
        uses: softprops/action-gh-release@v1
        if: runner.os == 'macOS'
        with:
          files: ./build/*.dmg
      - name: Release-EXE
        uses: softprops/action-gh-release@v1
        if: runner.os == 'Windows'
        with:
          files: ./build/*.exe