name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build