name: test
on: push
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.JPG_ACTION_TOKEN }}"
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: install
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          web: npm start
          electron: npm run start-electron

