name: test
on: push
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.JPG_ACTION_TOKEN }}"
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Start web server
        run: npm start
      - name: Start electron
        run: npm run start-electron
      - name: Cypress run
        uses: cypress-io/github-action@v2

