name: test
on: push
jobs:
  build-tests:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.JPG_ACTION_TOKEN }}"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
  cypress-test:
    runs-on: [self-hosted]
    env:
      GH_TOKEN: "${{ secrets.JPG_ACTION_TOKEN }}"
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm rebuild
          start: npm run start-test-server,npm start
          wait-on: 'http://localhost:3000'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

