name: test
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  test-tauri:
      strategy:
        fail-fast: false
        matrix:
          platform: [macos-latest, ubuntu-20.04, windows-latest]

      runs-on: ${{ matrix.platform }}
      steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Test Build Web app
        working-directory: src-web
        run: |
          npm install 
          npm run build
      - name: Test Build Tauri
        working-directory: src-tauri
        run: |
          cargo install
          cargo tauri build
